"""Add RSCA module tables

Revision ID: 06180c04250a
Revises: 0fe4a2820fe4
Create Date: 2025-09-23 13:18:53.421127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06180c04250a'
down_revision = '0fe4a2820fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rsca_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_siklus', sa.String(length=200), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsca_cycle_departments',
    sa.Column('rsca_cycle_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['rsca_cycle_id'], ['rsca_cycles.id'], ),
    sa.PrimaryKeyConstraint('rsca_cycle_id', 'department_id')
    )
    op.create_table('rsca_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['rsca_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsca_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('risk_register_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['rsca_cycles.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['rsca_questionnaires.id'], ),
    sa.ForeignKeyConstraint(['risk_register_id'], ['risk_register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsca_answers')
    op.drop_table('rsca_questionnaires')
    op.drop_table('rsca_cycle_departments')
    op.drop_table('rsca_cycles')
    op.drop_table('departments')
    # ### end Alembic commands ###
