"""Add question_type and control_rating to RSCA

Revision ID: 0f01de14b45e
Revises: 32d979c2072f
Create Date: 2025-11-09 11:30:08.163178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f01de14b45e'
down_revision = '32d979c2072f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsca_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_effectiveness_rating', sa.String(length=50), nullable=True))

    with op.batch_alter_table('rsca_questionnaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsca_questionnaires', schema=None) as batch_op:
        batch_op.drop_column('question_type')

    with op.batch_alter_table('rsca_answers', schema=None) as batch_op:
        batch_op.drop_column('control_effectiveness_rating')

    # ### end Alembic commands ###
