"""Create horizon_scan_entries table

Revision ID: 0fe4a2820fe4
Revises: bd45d9a62657
Create Date: 2025-09-23 10:29:02.639291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe4a2820fe4'
down_revision = 'bd45d9a62657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horizon_scan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('original_summary', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horizon_scan_entries')
    # ### end Alembic commands ###
