"""add assessment limits to user

Revision ID: 103ebe933a18
Revises: 22cff2672d13
Create Date: 2025-10-30 02:18:33.812161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103ebe933a18'
down_revision = '22cff2672d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_dasar', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limit_madya', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limit_ai', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('limit_ai')
        batch_op.drop_column('limit_madya')
        batch_op.drop_column('limit_dasar')

    # ### end Alembic commands ###
