"""add phone and institution to user

Revision ID: 22cff2672d13
Revises: fedd8d7daaae
Create Date: 2025-10-30 02:08:12.046012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cff2672d13'
down_revision = 'fedd8d7daaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('institution')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
