"""add sasaran organisasi kpi table

Revision ID: 23bc1af5ea77
Revises: bee318a96cb3
Create Date: 2025-10-20 09:03:12.474567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bc1af5ea77'
down_revision = 'bee318a96cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sasaran_organisasi_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sasaran_kpi', sa.Text(), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('inherent_risk_score', sa.Integer(), nullable=True),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sasaran_organisasi_kpi')
    # ### end Alembic commands ###
