"""Create main_risk_register table

Revision ID: 290e2200632b
Revises: 3891a56a35f6
Create Date: 2025-10-09 16:01:03.651255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290e2200632b'
down_revision = '3891a56a35f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_risk_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kode_risiko', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('risk_type', sa.String(length=50), nullable=True),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=True),
    sa.Column('risk_causes', sa.Text(), nullable=True),
    sa.Column('risk_impacts', sa.Text(), nullable=True),
    sa.Column('existing_controls', sa.Text(), nullable=True),
    sa.Column('control_effectiveness', sa.String(length=50), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('inherent_likelihood', sa.Integer(), nullable=True),
    sa.Column('inherent_impact', sa.Integer(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('treatment_option', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_risk_register')
    # ### end Alembic commands ###
