"""Add ai_summary and recommendations to RiskAssessment

Revision ID: 29cc6f2a2a0c
Revises: e79c93e48198
Create Date: 2025-10-09 10:09:41.601122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cc6f2a2a0c'
down_revision = 'e79c93e48198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_recommendations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_column('ai_recommendations')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
