"""Add limit_template_peta to User model

Revision ID: 2df2c289f506
Revises: 688f78dd7f8a
Create Date: 2025-11-11 17:10:29.201062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df2c289f506'
down_revision = '688f78dd7f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_template_peta', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('limit_template_peta')

    # ### end Alembic commands ###
