"""add madya criteria probability and impact tables

Revision ID: 32d979c2072f
Revises: e7684f105699
Create Date: 2025-11-04 11:10:27.778457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d979c2072f'
down_revision = 'e7684f105699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('madya_criteria_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('kriteriaDampak', sa.String(length=255), nullable=True),
    sa.Column('rangeFinansial', sa.Text(), nullable=True),
    sa.Column('deskripsiDampak1', sa.Text(), nullable=True),
    sa.Column('stra_dampak', sa.Text(), nullable=True),
    sa.Column('hukum_pelanggaran', sa.Text(), nullable=True),
    sa.Column('kepat_pelanggaran', sa.Text(), nullable=True),
    sa.Column('reput_keluhan', sa.Text(), nullable=True),
    sa.Column('reput_berita', sa.Text(), nullable=True),
    sa.Column('reput_saing', sa.Text(), nullable=True),
    sa.Column('sdm_keluhan', sa.Text(), nullable=True),
    sa.Column('sdm_turnover', sa.Text(), nullable=True),
    sa.Column('sdm_regretted_turnover', sa.Text(), nullable=True),
    sa.Column('sistem_gangguan', sa.Text(), nullable=True),
    sa.Column('sistem_siber', sa.Text(), nullable=True),
    sa.Column('sistem_platform', sa.Text(), nullable=True),
    sa.Column('ops_sla', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_1', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_2', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_3', sa.Text(), nullable=True),
    sa.Column('hsse_kerusakan_lingkungan', sa.Text(), nullable=True),
    sa.Column('hsse_penurunan_esg', sa.Text(), nullable=True),
    sa.Column('pmn_tunda', sa.Text(), nullable=True),
    sa.Column('bank_fraud', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_rating', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_peringkat', sa.Text(), nullable=True),
    sa.Column('aktu_rasio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madya_criteria_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('kemungkinan', sa.Text(), nullable=True),
    sa.Column('frekuensi', sa.Text(), nullable=True),
    sa.Column('persentase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('risk_map_criteria_impact')
    op.drop_table('risk_map_criteria_probability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_map_criteria_probability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parameter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('kemungkinan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('frekuensi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persentase', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], name=op.f('risk_map_criteria_probability_assessment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_map_criteria_probability_pkey'))
    )
    op.create_table('risk_map_criteria_impact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kriteriaDampak', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rangeFinansial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deskripsiDampak1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stra_dampak', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hukum_pelanggaran', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kepat_pelanggaran', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reput_keluhan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reput_berita', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reput_saing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sdm_keluhan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sdm_turnover', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sdm_regretted_turnover', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sistem_gangguan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sistem_siber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sistem_platform', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ops_sla', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsse_fatality_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsse_fatality_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsse_fatality_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsse_kerusakan_lingkungan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsse_penurunan_esg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pmn_tunda', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bank_fraud', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asuransi_aset_rating', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asuransi_aset_peringkat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aktu_rasio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], name=op.f('risk_map_criteria_impact_assessment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_map_criteria_impact_pkey'))
    )
    op.drop_table('madya_criteria_probability')
    op.drop_table('madya_criteria_impact')
    # ### end Alembic commands ###
