"""Add detailed AI analysis fields to RiskAssessment

Revision ID: 3891a56a35f6
Revises: 29cc6f2a2a0c
Create Date: 2025-10-09 11:30:22.628297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3891a56a35f6'
down_revision = '29cc6f2a2a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_executive_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_risk_profile_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_immediate_priorities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_critical_risks_discussion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_implementation_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_next_steps', sa.Text(), nullable=True))
        batch_op.drop_column('ai_recommendations')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_recommendations', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('ai_next_steps')
        batch_op.drop_column('ai_implementation_plan')
        batch_op.drop_column('ai_critical_risks_discussion')
        batch_op.drop_column('ai_immediate_priorities')
        batch_op.drop_column('ai_risk_profile_analysis')
        batch_op.drop_column('ai_executive_summary')

    # ### end Alembic commands ###
