"""Add basic_assessments table

Revision ID: 3cafa862c0bd
Revises: e09f19558251
Create Date: 2025-10-16 14:02:32.147003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cafa862c0bd'
down_revision = 'e09f19558251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_unit_kerja', sa.String(length=200), nullable=False),
    sa.Column('nama_perusahaan', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_assessments')
    # ### end Alembic commands ###
