"""Add ActionPlan table for risk treatment

Revision ID: 3dde55306a76
Revises: ba9b6c5e83b6
Create Date: 2025-11-18 09:13:03.573528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dde55306a76'
down_revision = 'ba9b6c5e83b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_department_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('origin_answer_id', sa.Integer(), nullable=True),
    sa.Column('origin_submitted_risk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['origin_answer_id'], ['rsca_answers.id'], ),
    sa.ForeignKeyConstraint(['origin_submitted_risk_id'], ['submitted_risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_plans')
    # ### end Alembic commands ###
