"""Add MasterData table

Revision ID: 3fdec49c8120
Revises: b991c7a288bf
Create Date: 2025-10-03 10:17:34.769824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdec49c8120'
down_revision = 'b991c7a288bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_data_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_data_category'))

    op.drop_table('master_data')
    # ### end Alembic commands ###
