"""Add BIA module tables

Revision ID: 4b6bc3e8099f
Revises: 68739a4a8064
Create Date: 2025-09-23 15:20:21.773146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6bc3e8099f'
down_revision = '68739a4a8064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_aset', sa.String(length=200), nullable=False),
    sa.Column('tipe_aset', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_skenario', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['critical_assets.id'], ),
    sa.ForeignKeyConstraint(['depends_on_asset_id'], ['critical_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    op.drop_table('impact_scenarios')
    op.drop_table('critical_assets')
    # ### end Alembic commands ###
