"""add template link to madya assessment

Revision ID: 5593ee8a054d
Revises: d85a445875a3
Create Date: 2025-10-20 14:42:48.909920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5593ee8a054d'
down_revision = 'd85a445875a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_map_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'risk_map_templates', ['risk_map_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('risk_map_template_id')

    # ### end Alembic commands ###
