"""Add BPR module tables

Revision ID: 68739a4a8064
Revises: fda9ac35c48d
Create Date: 2025-09-23 14:55:54.314987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68739a4a8064'
down_revision = 'fda9ac35c48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_proses', sa.String(length=250), nullable=False),
    sa.Column('pemilik_proses', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_langkah', sa.String(length=250), nullable=False),
    sa.Column('deskripsi_langkah', sa.Text(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_step_risks',
    sa.Column('process_step_id', sa.Integer(), nullable=False),
    sa.Column('risk_register_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_steps.id'], ),
    sa.ForeignKeyConstraint(['risk_register_id'], ['risk_register.id'], ),
    sa.PrimaryKeyConstraint('process_step_id', 'risk_register_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_step_risks')
    op.drop_table('process_steps')
    op.drop_table('business_processes')
    # ### end Alembic commands ###
