"""Add institution tenancy to Department and RscaCycle

Revision ID: 688f78dd7f8a
Revises: 0f01de14b45e
Create Date: 2025-11-09 22:48:06.204752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688f78dd7f8a'
down_revision = '0f01de14b45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))

    with op.batch_alter_table('rsca_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsca_cycles', schema=None) as batch_op:
        batch_op.drop_column('institution')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
