"""Create KRI table and add relationship to User

Revision ID: 6e74027d5e0f
Revises: 481dbe225239
Create Date: 2025-09-22 14:15:10.807707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e74027d5e0f'
down_revision = '481dbe225239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kri', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tipe_data', sa.String(length=50), nullable=False),
    sa.Column('ambang_batas_kritis', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kri')
    # ### end Alembic commands ###
