"""Update RiskRegister with detailed AI fields

Revision ID: 8935852ba21c
Revises: c9a936330718
Create Date: 2025-10-07 01:14:23.480958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8935852ba21c'
down_revision = 'c9a936330718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_causes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('risk_impacts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('existing_controls', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mitigation_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('inherent_likelihood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inherent_impact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('residual_likelihood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('residual_impact', sa.Integer(), nullable=True))
        batch_op.drop_column('level_risiko_inheren')
        batch_op.drop_column('level_risiko_kontrol')
        batch_op.drop_column('level_risiko_residual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_risiko_residual', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('level_risiko_kontrol', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('level_risiko_inheren', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('residual_impact')
        batch_op.drop_column('residual_likelihood')
        batch_op.drop_column('inherent_impact')
        batch_op.drop_column('inherent_likelihood')
        batch_op.drop_column('mitigation_plan')
        batch_op.drop_column('existing_controls')
        batch_op.drop_column('risk_impacts')
        batch_op.drop_column('risk_causes')

    # ### end Alembic commands ###
