"""add filter fields to madya assessment

Revision ID: 8c8aa2c8ed93
Revises: 5593ee8a054d
Create Date: 2025-10-27 13:39:07.324543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8aa2c8ed93'
down_revision = '5593ee8a054d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_organisasi', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filter_direktorat', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filter_divisi', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filter_departemen', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.drop_column('filter_departemen')
        batch_op.drop_column('filter_divisi')
        batch_op.drop_column('filter_direktorat')
        batch_op.drop_column('filter_organisasi')

    # ### end Alembic commands ###
