"""Add organizational context models and relationship

Revision ID: 8dca11bdcb0b
Revises: 3cafa862c0bd
Create Date: 2025-10-16 14:23:42.033999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dca11bdcb0b'
down_revision = '3cafa862c0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_context', sa.Text(), nullable=False),
    sa.Column('internal_context', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_assessment_contexts',
    sa.Column('basic_assessment_id', sa.Integer(), nullable=False),
    sa.Column('organizational_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_assessment_id'], ['basic_assessments.id'], ),
    sa.ForeignKeyConstraint(['organizational_context_id'], ['organizational_contexts.id'], ),
    sa.PrimaryKeyConstraint('basic_assessment_id', 'organizational_context_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_assessment_contexts')
    op.drop_table('organizational_contexts')
    # ### end Alembic commands ###
