"""Add basic risk identification table

Revision ID: 91ce165c426f
Revises: 8dca11bdcb0b
Create Date: 2025-10-16 14:41:42.394569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ce165c426f'
down_revision = '8dca11bdcb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_risk_identifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_risiko', sa.String(length=50), nullable=True),
    sa.Column('kategori_risiko', sa.String(length=100), nullable=False),
    sa.Column('unit_kerja', sa.String(length=200), nullable=False),
    sa.Column('sasaran', sa.Text(), nullable=True),
    sa.Column('tanggal_identifikasi', sa.Date(), nullable=False),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=False),
    sa.Column('akar_penyebab', sa.Text(), nullable=True),
    sa.Column('indikator_risiko', sa.Text(), nullable=True),
    sa.Column('internal_control', sa.Text(), nullable=True),
    sa.Column('deskripsi_dampak', sa.Text(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['basic_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_risk_identifications')
    # ### end Alembic commands ###
