"""add custom risk map scores table

Revision ID: 97e6fab93b98
Revises: 7623c020c455
Create Date: 2025-10-18 02:41:23.974704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e6fab93b98'
down_revision = '7623c020c455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_map_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('likelihood_level', sa.Integer(), nullable=False),
    sa.Column('impact_level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_map_scores')
    # ### end Alembic commands ###
