"""Add BPR module tables and remove old business process

Revision ID: af81cb4a714c
Revises: b87d0dbecafa
Create Date: 2025-11-19 23:07:18.040282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af81cb4a714c'
down_revision = 'b87d0dbecafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bpr_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('parent_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['bpr_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpr_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('react_flow_id', sa.String(length=100), nullable=False),
    sa.Column('source_node_ref', sa.String(length=100), nullable=False),
    sa.Column('target_node_ref', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('animated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['bpr_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpr_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('react_flow_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('style_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['bpr_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpr_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('risk_code', sa.String(length=50), nullable=True),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('risk_cause', sa.Text(), nullable=True),
    sa.Column('risk_impact', sa.Text(), nullable=True),
    sa.Column('existing_control', sa.Text(), nullable=True),
    sa.Column('control_effectiveness', sa.String(length=50), nullable=True),
    sa.Column('inherent_risk_level', sa.String(length=50), nullable=True),
    sa.Column('residual_risk_level', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['bpr_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('process_step_risks')
    op.drop_table('process_steps')
    op.drop_table('business_processes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_processes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('business_processes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_proses', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('pemilik_proses', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='business_processes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='business_processes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('process_steps',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('process_steps_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_langkah', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('deskripsi_langkah', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('urutan', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('process_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], name='process_steps_process_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='process_steps_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('process_step_risks',
    sa.Column('process_step_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_register_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_steps.id'], name=op.f('process_step_risks_process_step_id_fkey')),
    sa.ForeignKeyConstraint(['risk_register_id'], ['risk_register.id'], name=op.f('process_step_risks_risk_register_id_fkey')),
    sa.PrimaryKeyConstraint('process_step_id', 'risk_register_id', name=op.f('process_step_risks_pkey'))
    )
    op.drop_table('bpr_risks')
    op.drop_table('bpr_nodes')
    op.drop_table('bpr_edges')
    op.drop_table('bpr_documents')
    # ### end Alembic commands ###
