"""Add assessment_type to QrcAssessment

Revision ID: b3b082c31527
Revises: f1bace5e777f
Create Date: 2025-11-26 09:35:43.427185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b082c31527'
down_revision = 'f1bace5e777f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.drop_column('assessment_type')

    # ### end Alembic commands ###
