"""Add limit_horizon to users table

Revision ID: b87d0dbecafa
Revises: 3dde55306a76
Create Date: 2025-11-19 10:53:06.383960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87d0dbecafa'
down_revision = '3dde55306a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horizon_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('generated_title', sa.String(length=200), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('raw_news_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_horizon', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('limit_horizon')

    op.drop_table('horizon_scan_results')
    # ### end Alembic commands ###
