"""Refine RiskAssessment model fields

Revision ID: b991c7a288bf
Revises: 4b6bc3e8099f
Create Date: 2025-09-25 11:37:27.557306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b991c7a288bf'
down_revision = '4b6bc3e8099f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_assets', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('risk_limit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_categories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('project_objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relevant_regulations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('involved_departments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_actions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_risk_context', sa.Text(), nullable=True))
        batch_op.drop_column('deskripsi')
        batch_op.drop_column('ruang_lingkup')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruang_lingkup', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_risk_context')
        batch_op.drop_column('completed_actions')
        batch_op.drop_column('involved_departments')
        batch_op.drop_column('relevant_regulations')
        batch_op.drop_column('project_objective')
        batch_op.drop_column('risk_categories')
        batch_op.drop_column('risk_limit')
        batch_op.drop_column('currency')
        batch_op.drop_column('company_assets')
        batch_op.drop_column('company_type')
        batch_op.drop_column('company_industry')

    # ### end Alembic commands ###
