"""Add SubmittedRisk table for bottom-up risk submissions

Revision ID: ba9b6c5e83b6
Revises: 2df2c289f506
Create Date: 2025-11-17 16:47:32.360242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9b6c5e83b6'
down_revision = '2df2c289f506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('potential_cause', sa.Text(), nullable=True),
    sa.Column('potential_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['rsca_cycles.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_risks')
    # ### end Alembic commands ###
