"""Create risk assessment and risk register tables

Revision ID: bd45d9a62657
Revises: 6e74027d5e0f
Create Date: 2025-09-23 09:40:36.444643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd45d9a62657'
down_revision = '6e74027d5e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_asesmen', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('ruang_lingkup', sa.Text(), nullable=True),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_risiko', sa.String(length=20), nullable=False),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=False),
    sa.Column('level_risiko_inheren', sa.String(length=50), nullable=True),
    sa.Column('level_risiko_kontrol', sa.String(length=50), nullable=True),
    sa.Column('level_risiko_residual', sa.String(length=50), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_risiko')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_register')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
