"""move structure image from entry to assessment

Revision ID: bee318a96cb3
Revises: fabad70913c7
Create Date: 2025-10-19 19:04:55.433708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee318a96cb3'
down_revision = 'fabad70913c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_image_filename', sa.String(length=300), nullable=True))

    with op.batch_alter_table('organizational_structure_entries', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizational_structure_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.drop_column('structure_image_filename')

    # ### end Alembic commands ###
