"""Add QRC limits and archive flag

Revision ID: c2ec40c77b2f
Revises: b890a48f1d23
Create Date: 2025-11-26 16:10:27.110860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ec40c77b2f'
down_revision = 'b890a48f1d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_qrc_assessments_is_archived'), ['is_archived'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_qrc_standard', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limit_qrc_essay', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('limit_qrc_essay')
        batch_op.drop_column('limit_qrc_standard')

    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qrc_assessments_is_archived'))
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
