"""Add basic risk analysis table

Revision ID: c937ca5f5c08
Revises: 91ce165c426f
Create Date: 2025-10-16 16:39:15.727618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c937ca5f5c08'
down_revision = '91ce165c426f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_risk_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_identification_id', sa.Integer(), nullable=False),
    sa.Column('probabilitas', sa.Integer(), nullable=True),
    sa.Column('dampak', sa.Integer(), nullable=True),
    sa.Column('probabilitas_kualitatif', sa.Float(), nullable=True),
    sa.Column('dampak_finansial', sa.Float(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['basic_assessments.id'], ),
    sa.ForeignKeyConstraint(['risk_identification_id'], ['basic_risk_identifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_identification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_risk_analysis')
    # ### end Alembic commands ###
