"""Add Regulation table

Revision ID: c9a936330718
Revises: 3fdec49c8120
Create Date: 2025-10-03 15:19:34.123658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a936330718'
down_revision = '3fdec49c8120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_name'))

    op.drop_table('regulations')
    # ### end Alembic commands ###
