"""add risk input madya table

Revision ID: d85a445875a3
Revises: 23bc1af5ea77
Create Date: 2025-10-20 12:36:44.775726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85a445875a3'
down_revision = '23bc1af5ea77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_input_madya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sasaran_id', sa.Integer(), nullable=True),
    sa.Column('kode_risiko', sa.String(length=50), nullable=True),
    sa.Column('status_risiko', sa.String(length=50), nullable=True),
    sa.Column('peluang_ancaman', sa.String(length=50), nullable=True),
    sa.Column('kategori_risiko', sa.String(length=100), nullable=True),
    sa.Column('kategori_risiko_lainnya', sa.String(length=200), nullable=True),
    sa.Column('unit_kerja', sa.String(length=200), nullable=True),
    sa.Column('tanggal_identifikasi', sa.Date(), nullable=True),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=True),
    sa.Column('akar_penyebab', sa.Text(), nullable=True),
    sa.Column('indikator_risiko', sa.Text(), nullable=True),
    sa.Column('internal_control', sa.Text(), nullable=True),
    sa.Column('deskripsi_dampak', sa.Text(), nullable=True),
    sa.Column('inherent_probabilitas', sa.Integer(), nullable=True),
    sa.Column('inherent_dampak', sa.Integer(), nullable=True),
    sa.Column('inherent_skor', sa.Integer(), nullable=True),
    sa.Column('inherent_prob_kualitatif', sa.Float(), nullable=True),
    sa.Column('inherent_dampak_finansial', sa.Float(), nullable=True),
    sa.Column('inherent_nilai_bersih', sa.Float(), nullable=True),
    sa.Column('pemilik_risiko', sa.String(length=150), nullable=True),
    sa.Column('jabatan_pemilik', sa.String(length=150), nullable=True),
    sa.Column('kontak_pemilik_hp', sa.String(length=50), nullable=True),
    sa.Column('kontak_pemilik_email', sa.String(length=120), nullable=True),
    sa.Column('strategi', sa.String(length=100), nullable=True),
    sa.Column('rencana_penanganan', sa.Text(), nullable=True),
    sa.Column('biaya_penanganan', sa.Float(), nullable=True),
    sa.Column('penanganan_dilakukan', sa.Text(), nullable=True),
    sa.Column('status_penanganan', sa.String(length=50), nullable=True),
    sa.Column('jadwal_mulai_penanganan', sa.Date(), nullable=True),
    sa.Column('jadwal_selesai_penanganan', sa.Date(), nullable=True),
    sa.Column('pic_penanganan', sa.String(length=150), nullable=True),
    sa.Column('residual_probabilitas', sa.Integer(), nullable=True),
    sa.Column('residual_dampak', sa.Integer(), nullable=True),
    sa.Column('residual_skor', sa.Integer(), nullable=True),
    sa.Column('residual_prob_kualitatif', sa.Float(), nullable=True),
    sa.Column('residual_dampak_finansial', sa.Float(), nullable=True),
    sa.Column('residual_nilai_bersih', sa.Float(), nullable=True),
    sa.Column('tanggal_review', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.ForeignKeyConstraint(['sasaran_id'], ['sasaran_organisasi_kpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_input_madya')
    # ### end Alembic commands ###
