"""add nama_asesmen to madya_assessment

Revision ID: dd4d13cdbe2f
Revises: 8c8aa2c8ed93
Create Date: 2025-10-27 15:21:22.355345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4d13cdbe2f'
down_revision = '8c8aa2c8ed93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_asesmen', sa.String(length=200), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('madya_assessments', schema=None) as batch_op:
        batch_op.drop_column('nama_asesmen')

    # ### end Alembic commands ###
