"""Add department link to user

Revision ID: deedd0cee806
Revises: 06180c04250a
Create Date: 2025-09-23 13:28:12.784648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deedd0cee806'
down_revision = '06180c04250a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        # ↓↓↓ PERUBAHAN DI SINI ↓↓↓
        batch_op.create_foreign_key(
            'fk_users_departments_department_id',  # <-- Kita beri nama yang jelas
            'departments', ['department_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # ↓↓↓ PERUBAHAN DI SINI ↓↓↓
        batch_op.drop_constraint(
            'fk_users_departments_department_id',  # <-- Kita gunakan nama yang sama untuk menghapus
            type_='foreignkey'
        )
        batch_op.drop_column('department_id')
    # ### end Alembic commands ###