"""Add title column to risk registers

Revision ID: e09f19558251
Revises: 290e2200632b
Create Date: 2025-10-13 10:14:42.961395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09f19558251'
down_revision = '290e2200632b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_risk_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('main_risk_register', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
