"""Relink criteria models to MadyaAssessment

Revision ID: e7684f105699
Revises: f68acdd05635
Create Date: 2025-11-04 10:43:41.018419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7684f105699'
down_revision = 'f68acdd05635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_map_criteria_impact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('risk_map_criteria_impact_template_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'madya_assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('template_id')

    with op.batch_alter_table('risk_map_criteria_probability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('risk_map_criteria_probability_template_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'madya_assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_map_criteria_probability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('risk_map_criteria_probability_template_id_fkey'), 'risk_map_templates', ['template_id'], ['id'])
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('risk_map_criteria_impact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('risk_map_criteria_impact_template_id_fkey'), 'risk_map_templates', ['template_id'], ['id'])
        batch_op.drop_column('assessment_id')

    # ### end Alembic commands ###
