"""Add final detailed fields to RiskRegister

Revision ID: e79c93e48198
Revises: 8935852ba21c
Create Date: 2025-10-07 01:41:25.612508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79c93e48198'
down_revision = '8935852ba21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('risk_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('control_effectiveness', sa.String(length=50), nullable=True))
        batch_op.alter_column('deskripsi_risiko',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.alter_column('deskripsi_risiko',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('control_effectiveness')
        batch_op.drop_column('risk_type')
        batch_op.drop_column('objective')

    # ### end Alembic commands ###
