"""Add QrcAssessment table and update user roles

Revision ID: f1bace5e777f
Revises: af81cb4a714c
Create Date: 2025-11-25 17:11:01.559444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1bace5e777f'
down_revision = 'af81cb4a714c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qrc_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('answers_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('consultant_notes', sa.Text(), nullable=True),
    sa.Column('ai_generated_analysis', sa.Text(), nullable=True),
    sa.Column('final_report_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qrc_assessments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrc_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qrc_assessments_status'))

    op.drop_table('qrc_assessments')
    # ### end Alembic commands ###
