"""add risk map criteria tables

Revision ID: f68acdd05635
Revises: 103ebe933a18
Create Date: 2025-11-04 10:26:16.312061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68acdd05635'
down_revision = '103ebe933a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_map_criteria_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('kriteriaDampak', sa.String(length=255), nullable=True),
    sa.Column('rangeFinansial', sa.Text(), nullable=True),
    sa.Column('deskripsiDampak1', sa.Text(), nullable=True),
    sa.Column('stra_dampak', sa.Text(), nullable=True),
    sa.Column('hukum_pelanggaran', sa.Text(), nullable=True),
    sa.Column('kepat_pelanggaran', sa.Text(), nullable=True),
    sa.Column('reput_keluhan', sa.Text(), nullable=True),
    sa.Column('reput_berita', sa.Text(), nullable=True),
    sa.Column('reput_saing', sa.Text(), nullable=True),
    sa.Column('sdm_keluhan', sa.Text(), nullable=True),
    sa.Column('sdm_turnover', sa.Text(), nullable=True),
    sa.Column('sdm_regretted_turnover', sa.Text(), nullable=True),
    sa.Column('sistem_gangguan', sa.Text(), nullable=True),
    sa.Column('sistem_siber', sa.Text(), nullable=True),
    sa.Column('sistem_platform', sa.Text(), nullable=True),
    sa.Column('ops_sla', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_1', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_2', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_3', sa.Text(), nullable=True),
    sa.Column('hsse_kerusakan_lingkungan', sa.Text(), nullable=True),
    sa.Column('hsse_penurunan_esg', sa.Text(), nullable=True),
    sa.Column('pmn_tunda', sa.Text(), nullable=True),
    sa.Column('bank_fraud', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_rating', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_peringkat', sa.Text(), nullable=True),
    sa.Column('aktu_rasio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_criteria_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('kemungkinan', sa.Text(), nullable=True),
    sa.Column('frekuensi', sa.Text(), nullable=True),
    sa.Column('persentase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_map_criteria_probability')
    op.drop_table('risk_map_criteria_impact')
    # ### end Alembic commands ###
