"""add madya assessment and structure entry models

Revision ID: fabad70913c7
Revises: 97e6fab93b98
Create Date: 2025-10-19 18:47:17.512259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabad70913c7'
down_revision = '97e6fab93b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('madya_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_structure_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('direktorat', sa.String(length=200), nullable=True),
    sa.Column('divisi', sa.String(length=200), nullable=True),
    sa.Column('unit_kerja', sa.String(length=200), nullable=True),
    sa.Column('image_filename', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizational_structure_entries')
    op.drop_table('madya_assessments')
    # ### end Alembic commands ###
